// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Test = require("./Test.bs.js");
var React = require("react");
var ReactDom = require("react-dom");

var root = document.querySelector("#root");

if (!(root == null)) {
  ReactDom.render(React.createElement(Test.make, {}), root);
}

/* root Not a pure module */
